name: fissa-example-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - mkl_fft>=1.0.10
  - mkl>=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib>=2.0.2
  - scipy>=0.19.0
  - pip:
    - fissa[plotting]
    - sima
    - suite2p
